### ISSUE TITLE
Nothing in terminal

### ISSUE THREAD

**Issue by solsticedhiver** [M0Rf30/qemu-kernel-rpi#1]
Pardon my newbiness, but I was able to get it working with an older kernel 4.19.79-1 from your older repo, with that helper script:

```
#!/bin/bash
sudo qemu-system-arm \
	-kernel ~/qemu_vms/qemu-kernel-4.19.95-arch \
	-cpu arm1176 \
	-m 256 \
	-M versatilepb \
	-serial mon:stdio \
	-append "root=/dev/sda2 rootfstype=ext4 rw console=ttyS0" \
	-hda ~/qemu_vms/siarnaq.qcow \
	-no-reboot \
	-curses \
	-net nic -net bridge,br=br0
```

But now, I only have a blank terminal, and I wonder if the VM is even booting (started at all ?)

Is it me and my setup or has it somethiing to do with your kernel or config ?

I tried both your kernel config and the *archlijnux* kernel config for rpi0. It is the same

**Comment by M0Rf30** [comment]
I will investigate in the next days. in the meantime you can download a working version from my simonpi repo, under simonpiemu/kernels/rpi

**Comment by solsticedhiver** [comment]
I am using the *distccd-alarm-armv6h* package on archlinux that provides the arm toolchain from archlinux-arm `arm-unknown-linux-gnueabihf`. I also tweaked the build.sh file like that if it is relevant:

```
diff --git a/build.sh b/build.sh
index f217e28..1296064 100755
--- a/build.sh
+++ b/build.sh
@@ -5,7 +5,8 @@
 #######################################################
 MODEL=rpi1
 REMOTE=https://github.com/raspberrypi/linux
-TOOLCHAIN=arm-none-eabi
+TOOLCHAIN=arm-unknown-linux-gnueabihf
+PATH="$PATH:/opt/x-tools6h/arm-unknown-linux-gnueabihf/bin/"
 COMMIT=$(git remote show "$REMOTE" | grep "HEAD" | cut -f 2 -d : | tr -d '[:space:]')
 export ARCH=arm
 export CROSS_COMPILE=${TOOLCHAIN}-
```

**Comment by M0Rf30** [comment]
try with this one
```
qemu-system-arm -nographic -cpu arm1176 -m 256 -M versatilepb -drive file=/home/morfeo/.simonpi/sd-arch-rpi-qemu.img,if=scsi,format=raw,cache=none \
 -kernel ~/qemu_vms/qemu-kernel-4.19.95-arch \ 
-no-reboot -append 'root=/dev/sda2 fstab=no rootfstype=ext4 rw console=ttyAMA0 quiet audit=0 panic=1' \
-initrd <your-initrd> \ 
-net nic,macaddr=52:54:31:73:be:3f \
-net tap,ifname=<your_tap_device>,script=no,downscript=no
```
initrd is not required.
your_tap_device is a tap interface configured in such a way to give connectivity to the guest, combined with a well configured dns server on top of it

Here the latest kernel works like a charm with simonpi tool
